Rename variable 'inp' because of colliding definition in Cygwin.
Although this is probably not the application's fault and this
was found with gcc 4.5.3 using Windows 64-bit cross-compiling only.

windowfocus.cxx:25:18: error: 'Fl_Input* inp' redeclared as different kind of symbol
/usr/x86_64-w64-mingw32/sys-root/mingw/include/intrin.h:347:5: error: previous declaration of 'int inp(short unsigned int)'